# Copyright (c) 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# GNU Makefile based on shared rules provided by the Native Client SDK.
# See README.Makefiles for more details.

VALID_TOOLCHAINS := newlib pnacl emscripten

ifeq (,$(NACL_SDK_ROOT))
  $(error NACL_SDK_ROOT is not set.)
endif
ifeq (,$(PEPPERJS_SRC_ROOT))
  include $(NACL_SDK_ROOT)/tools/common.mk
else
  include $(PEPPERJS_SRC_ROOT)/tools/common.mk
endif

USE_FLOAT = 1
USE_WISDOM = 0
USE_THREADS = 0

TARGET = smoothnacl

ifeq (1,$(USE_FLOAT))
  ifeq (1,$(USE_THREADS))
    LIBS = fftw3f_threads
  endif
  LIBS += fftw3f
  CFLAGS = -DUSE_FLOAT -Dreal=float
else
  ifeq (1,$(USE_THREADS))
    LIBS = fftw3_threads
  endif
  LIBS += fftw3
  CFLAGS = -Dreal=double
endif
LIBS += ppapi_cpp ppapi pthread

ifeq (1,$(USE_THREADS))
  CFLAGS += -DUSE_THREADS
endif

CFLAGS += -Wall -Isrc
SOURCES = \
  src/app.cc \
  src/functions.cc \
  src/kernel.cc \
  src/palette.cc \
  src/simulation.cc \
  src/smoother.cc

ifeq (1,$(USE_WISDOM))
  SOURCES += \
    wisdom/i686.double.x.cc \
    wisdom/i686.float.x.cc \
    wisdom/pnacl.double.x.cc \
    wisdom/pnacl.float.x.cc \
    wisdom/x86-64.double.x.cc \
    wisdom/x86-64.float.x.cc
  CFLAGS += -DUSE_WISDOM
endif

ifeq (emscripten,$(TOOLCHAIN))
  CFLAGS += -I$(PEPPERJS_SRC_ROOT)/emscripten/usr/include
  LDFLAGS += -L$(PEPPERJS_SRC_ROOT)/emscripten/usr/lib
endif


.PHONY: ports
ports:
	@build/build_ports.sh

# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

ifeq ($(CONFIG),Release)
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS),$(LDFLAGS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS),$(LDFLAGS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))
