# Copyright (c) 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# GNU Makefile based on shared rules provided by the Native Client SDK.
# See README.Makefiles for more details.

VALID_TOOLCHAINS := newlib glibc pnacl

ifeq (,$(NACL_SDK_ROOT))
  $(error NACL_SDK_ROOT is not set.)
endif
include $(NACL_SDK_ROOT)/tools/common.mk

USE_FLOAT = 1
USE_WISDOM = 1
USE_THREADS = 1

TARGET = smoothnacl

ifeq (1,$(USE_FLOAT))
  ifeq (1,$(USE_THREADS))
    LIBS = fftw3f_threads
  endif
  LIBS += fftw3f
  CFLAGS = -DUSE_FLOAT -Dreal=float
  PORT = fftw-float
else
  ifeq (1,$(USE_THREADS))
    LIBS = fftw3_threads
  endif
  LIBS += fftw3
  CFLAGS = -Dreal=double
  PORT = fftw
endif
LIBS += ppapi_cpp ppapi pthread

ifeq (1,$(USE_THREADS))
  CFLAGS += -DUSE_THREADS
endif

CFLAGS += -Wall -Isrc
SOURCES = \
  src/app.cc \
  src/functions.cc \
  src/kernel.cc \
  src/palette.cc \
  src/simulation.cc \
  src/smoother.cc

ifeq (1,$(USE_WISDOM))
  SOURCES += \
    wisdom/i686.double.x.cc \
    wisdom/i686.float.x.cc \
    wisdom/pnacl.double.x.cc \
    wisdom/pnacl.float.x.cc \
    wisdom/x86-64.double.x.cc \
    wisdom/x86-64.float.x.cc
  CFLAGS += -DUSE_WISDOM
endif


.PHONY: ports
ports:
ifeq (newlib,$(TOOLCHAIN))
	$(MAKE) -C third_party/webports/src $(PORT) NACL_ARCH=i686
	$(MAKE) -C third_party/webports/src $(PORT) NACL_ARCH=x86_64
	$(MAKE) -C third_party/webports/src $(PORT) NACL_ARCH=arm
endif
ifeq (pnacl,$(TOOLCHAIN))
	$(MAKE) -C third_party/webports/src $(PORT) TOOLCHAIN=pnacl
endif

# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

ifeq ($(CONFIG),Release)
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))
