# Copyright (c) 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# GNU Makefile based on shared rules provided by the Native Client SDK.
# See README.Makefiles for more details.

VALID_TOOLCHAINS := newlib glibc pnacl

ifeq (,$(NACL_SDK_ROOT))
  $(error NACL_SDK_ROOT is not set.)
endif
include $(NACL_SDK_ROOT)/tools/common.mk


TARGET = smoothnacl
LIBS = fftw3 ppapi_simple nacl_io ppapi_cpp ppapi pthread

CFLAGS = -Wall
SOURCES = \
  src/app.cc \
  src/functions.cc \
  src/kernel.cc \
  src/main.cc \
  src/palette.cc \
  src/simulation.cc \
  src/smoother.cc

.PHONY: ports
ports:
	@build/build_ports.sh

# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

ifeq ($(CONFIG),Release)
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))
