// Copyright 2013 Ben Smith. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#define glActiveTexture GLES2_GET_FUN(ActiveTexture)
#define glAttachShader GLES2_GET_FUN(AttachShader)
#define glBindAttribLocation GLES2_GET_FUN(BindAttribLocation)
#define glBindBuffer GLES2_GET_FUN(BindBuffer)
#define glBindFramebuffer GLES2_GET_FUN(BindFramebuffer)
#define glBindRenderbuffer GLES2_GET_FUN(BindRenderbuffer)
#define glBindTexture GLES2_GET_FUN(BindTexture)
#define glBlendColor GLES2_GET_FUN(BlendColor)
#define glBlendEquation GLES2_GET_FUN(BlendEquation)
#define glBlendEquationSeparate GLES2_GET_FUN(BlendEquationSeparate)
#define glBlendFunc GLES2_GET_FUN(BlendFunc)
#define glBlendFuncSeparate GLES2_GET_FUN(BlendFuncSeparate)
#define glBufferData GLES2_GET_FUN(BufferData)
#define glBufferSubData GLES2_GET_FUN(BufferSubData)
#define glCheckFramebufferStatus GLES2_GET_FUN(CheckFramebufferStatus)
#define glClear GLES2_GET_FUN(Clear)
#define glClearColor GLES2_GET_FUN(ClearColor)
#define glClearDepthf GLES2_GET_FUN(ClearDepthf)
#define glClearStencil GLES2_GET_FUN(ClearStencil)
#define glColorMask GLES2_GET_FUN(ColorMask)
#define glCompileShader GLES2_GET_FUN(CompileShader)
#define glCompressedTexImage2D GLES2_GET_FUN(CompressedTexImage2D)
#define glCompressedTexSubImage2D GLES2_GET_FUN(CompressedTexSubImage2D)
#define glCopyTexImage2D GLES2_GET_FUN(CopyTexImage2D)
#define glCopyTexSubImage2D GLES2_GET_FUN(CopyTexSubImage2D)
#define glCreateProgram GLES2_GET_FUN(CreateProgram)
#define glCreateShader GLES2_GET_FUN(CreateShader)
#define glCullFace GLES2_GET_FUN(CullFace)
#define glDeleteBuffers GLES2_GET_FUN(DeleteBuffers)
#define glDeleteFramebuffers GLES2_GET_FUN(DeleteFramebuffers)
#define glDeleteProgram GLES2_GET_FUN(DeleteProgram)
#define glDeleteRenderbuffers GLES2_GET_FUN(DeleteRenderbuffers)
#define glDeleteShader GLES2_GET_FUN(DeleteShader)
#define glDeleteTextures GLES2_GET_FUN(DeleteTextures)
#define glDepthFunc GLES2_GET_FUN(DepthFunc)
#define glDepthMask GLES2_GET_FUN(DepthMask)
#define glDepthRangef GLES2_GET_FUN(DepthRangef)
#define glDetachShader GLES2_GET_FUN(DetachShader)
#define glDisable GLES2_GET_FUN(Disable)
#define glDisableVertexAttribArray GLES2_GET_FUN(DisableVertexAttribArray)
#define glDrawArrays GLES2_GET_FUN(DrawArrays)
#define glDrawElements GLES2_GET_FUN(DrawElements)
#define glEnable GLES2_GET_FUN(Enable)
#define glEnableVertexAttribArray GLES2_GET_FUN(EnableVertexAttribArray)
#define glFinish GLES2_GET_FUN(Finish)
#define glFlush GLES2_GET_FUN(Flush)
#define glFramebufferRenderbuffer GLES2_GET_FUN(FramebufferRenderbuffer)
#define glFramebufferTexture2D GLES2_GET_FUN(FramebufferTexture2D)
#define glFrontFace GLES2_GET_FUN(FrontFace)
#define glGenBuffers GLES2_GET_FUN(GenBuffers)
#define glGenerateMipmap GLES2_GET_FUN(GenerateMipmap)
#define glGenFramebuffers GLES2_GET_FUN(GenFramebuffers)
#define glGenRenderbuffers GLES2_GET_FUN(GenRenderbuffers)
#define glGenTextures GLES2_GET_FUN(GenTextures)
#define glGetActiveAttrib GLES2_GET_FUN(GetActiveAttrib)
#define glGetActiveUniform GLES2_GET_FUN(GetActiveUniform)
#define glGetAttachedShaders GLES2_GET_FUN(GetAttachedShaders)
#define glGetAttribLocation GLES2_GET_FUN(GetAttribLocation)
#define glGetBooleanv GLES2_GET_FUN(GetBooleanv)
#define glGetBufferParameteriv GLES2_GET_FUN(GetBufferParameteriv)
#define glGetError GLES2_GET_FUN(GetError)
#define glGetFloatv GLES2_GET_FUN(GetFloatv)
#define glGetFramebufferAttachmentParameteriv GLES2_GET_FUN(GetFramebufferAttachmentParameteriv)
#define glGetIntegerv GLES2_GET_FUN(GetIntegerv)
#define glGetProgramiv GLES2_GET_FUN(GetProgramiv)
#define glGetProgramInfoLog GLES2_GET_FUN(GetProgramInfoLog)
#define glGetRenderbufferParameteriv GLES2_GET_FUN(GetRenderbufferParameteriv)
#define glGetShaderiv GLES2_GET_FUN(GetShaderiv)
#define glGetShaderInfoLog GLES2_GET_FUN(GetShaderInfoLog)
#define glGetShaderPrecisionFormat GLES2_GET_FUN(GetShaderPrecisionFormat)
#define glGetShaderSource GLES2_GET_FUN(GetShaderSource)
#define glGetString GLES2_GET_FUN(GetString)
#define glGetTexParameterfv GLES2_GET_FUN(GetTexParameterfv)
#define glGetTexParameteriv GLES2_GET_FUN(GetTexParameteriv)
#define glGetUniformfv GLES2_GET_FUN(GetUniformfv)
#define glGetUniformiv GLES2_GET_FUN(GetUniformiv)
#define glGetUniformLocation GLES2_GET_FUN(GetUniformLocation)
#define glGetVertexAttribfv GLES2_GET_FUN(GetVertexAttribfv)
#define glGetVertexAttribiv GLES2_GET_FUN(GetVertexAttribiv)
#define glGetVertexAttribPointerv GLES2_GET_FUN(GetVertexAttribPointerv)
#define glHint GLES2_GET_FUN(Hint)
#define glIsBuffer GLES2_GET_FUN(IsBuffer)
#define glIsEnabled GLES2_GET_FUN(IsEnabled)
#define glIsFramebuffer GLES2_GET_FUN(IsFramebuffer)
#define glIsProgram GLES2_GET_FUN(IsProgram)
#define glIsRenderbuffer GLES2_GET_FUN(IsRenderbuffer)
#define glIsShader GLES2_GET_FUN(IsShader)
#define glIsTexture GLES2_GET_FUN(IsTexture)
#define glLineWidth GLES2_GET_FUN(LineWidth)
#define glLinkProgram GLES2_GET_FUN(LinkProgram)
#define glPixelStorei GLES2_GET_FUN(PixelStorei)
#define glPolygonOffset GLES2_GET_FUN(PolygonOffset)
#define glReadPixels GLES2_GET_FUN(ReadPixels)
#define glReleaseShaderCompiler GLES2_GET_FUN(ReleaseShaderCompiler)
#define glRenderbufferStorage GLES2_GET_FUN(RenderbufferStorage)
#define glSampleCoverage GLES2_GET_FUN(SampleCoverage)
#define glScissor GLES2_GET_FUN(Scissor)
#define glShaderBinary GLES2_GET_FUN(ShaderBinary)
#define glShaderSource GLES2_GET_FUN(ShaderSource)
#define glStencilFunc GLES2_GET_FUN(StencilFunc)
#define glStencilFuncSeparate GLES2_GET_FUN(StencilFuncSeparate)
#define glStencilMask GLES2_GET_FUN(StencilMask)
#define glStencilMaskSeparate GLES2_GET_FUN(StencilMaskSeparate)
#define glStencilOp GLES2_GET_FUN(StencilOp)
#define glStencilOpSeparate GLES2_GET_FUN(StencilOpSeparate)
#define glTexImage2D GLES2_GET_FUN(TexImage2D)
#define glTexParameterf GLES2_GET_FUN(TexParameterf)
#define glTexParameterfv GLES2_GET_FUN(TexParameterfv)
#define glTexParameteri GLES2_GET_FUN(TexParameteri)
#define glTexParameteriv GLES2_GET_FUN(TexParameteriv)
#define glTexSubImage2D GLES2_GET_FUN(TexSubImage2D)
#define glUniform1f GLES2_GET_FUN(Uniform1f)
#define glUniform1fv GLES2_GET_FUN(Uniform1fv)
#define glUniform1i GLES2_GET_FUN(Uniform1i)
#define glUniform1iv GLES2_GET_FUN(Uniform1iv)
#define glUniform2f GLES2_GET_FUN(Uniform2f)
#define glUniform2fv GLES2_GET_FUN(Uniform2fv)
#define glUniform2i GLES2_GET_FUN(Uniform2i)
#define glUniform2iv GLES2_GET_FUN(Uniform2iv)
#define glUniform3f GLES2_GET_FUN(Uniform3f)
#define glUniform3fv GLES2_GET_FUN(Uniform3fv)
#define glUniform3i GLES2_GET_FUN(Uniform3i)
#define glUniform3iv GLES2_GET_FUN(Uniform3iv)
#define glUniform4f GLES2_GET_FUN(Uniform4f)
#define glUniform4fv GLES2_GET_FUN(Uniform4fv)
#define glUniform4i GLES2_GET_FUN(Uniform4i)
#define glUniform4iv GLES2_GET_FUN(Uniform4iv)
#define glUniformMatrix2fv GLES2_GET_FUN(UniformMatrix2fv)
#define glUniformMatrix3fv GLES2_GET_FUN(UniformMatrix3fv)
#define glUniformMatrix4fv GLES2_GET_FUN(UniformMatrix4fv)
#define glUseProgram GLES2_GET_FUN(UseProgram)
#define glValidateProgram GLES2_GET_FUN(ValidateProgram)
#define glVertexAttrib1f GLES2_GET_FUN(VertexAttrib1f)
#define glVertexAttrib1fv GLES2_GET_FUN(VertexAttrib1fv)
#define glVertexAttrib2f GLES2_GET_FUN(VertexAttrib2f)
#define glVertexAttrib2fv GLES2_GET_FUN(VertexAttrib2fv)
#define glVertexAttrib3f GLES2_GET_FUN(VertexAttrib3f)
#define glVertexAttrib3fv GLES2_GET_FUN(VertexAttrib3fv)
#define glVertexAttrib4f GLES2_GET_FUN(VertexAttrib4f)
#define glVertexAttrib4fv GLES2_GET_FUN(VertexAttrib4fv)
#define glVertexAttribPointer GLES2_GET_FUN(VertexAttribPointer)
#define glViewport GLES2_GET_FUN(Viewport)

